# Generated by Django 5.1.4 on 2024-12-17 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='category',
            field=models.CharField(default='Uncategorized', max_length=100),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='experience_level',
            field=models.CharField(default='Uncategorized', max_length=50),
            preserve_default=False,
        ),
    ]
