# Generated by Django 5.1.4 on 2024-12-26 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_employerprofile_jobseekerprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
